# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Install Dependencies
        run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: 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
          NPM_TOKEN: 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
        run: npm run semantic-release

  # quality:

  #   runs-on: ${{ matrix.os }}

  #   strategy:
  #     matrix:
  #       node-version: [10.x, 12.x, 14.x, 15.x]
  #       os: [ubuntu-latest, windows-latest]
  #       # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - run: npm ci
  #   - run: npm test

  # publish:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.ref == 'refs/heads/main' }}
  #   needs: [quality]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - run: npm ci
  #   - run: npm run semantic-release
  #     env:
  #       NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
